#test model:
test_model: 
        - DLRM
        - WDL
          #- DeepFM
          #- DSSM
          #- DIEN
          #- DIN
          #- ESMM
          #- DBMTL
          #- MMoE
          #- SimpleMultiTask
        - BST

#test images
deeprec_test_image: cesg-prc-registry.cn-beijing.cr.aliyuncs.com/cesg-ali/deeprec-modelzoo:220713-deeprec2206
tf_test_image: cesg-prc-registry.cn-beijing.cr.aliyuncs.com/cesg-ali/deeprec-modelzoo:tf

#batchsize map<model,batchsize>
model_batchsize:
  WDL: 512
  DLRM: 512
  DeepFM: 512
  DSSM: 4096
  DIEN: 512
  DIN: 512
  ESMM: 512
  DBMTL: 512
  MMoE: 512
  SimpleMultiTask: 512
  BST: 512

#args for deeprec
#like --emb_fusion true
modelArgs: --no_eval

#tf on/off
stocktf: on

# set cpu
cpu_sets: 

#set gpu
gpu_sets: 

# env config 
env_var:
  - export START_STATISTIC_STEP=100
  - export STOP_STATISTIC_STEP=110


